---
# source: https://www.middlewareinventory.com/blog/ansible-get-ip-address/

- name: Get SSH IP Address
  ansible.builtin.set_fact:
    ssh_ip_address: hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]
