---
- name: Get running services
  ansible.builtin.service_facts:
  register: service_facts_run

- name: Debug variable ansible_facts.services
  ansible.builtin.debug:
    var: ansible_facts.services
    verbosity: 2
