---
- name: Debug variable inventory_hostname
  ansible.builtin.debug:
    var: inventory_hostname

- name: Debug variable ansible_hostname
  ansible.builtin.debug:
    var: ansible_hostname

- name: Debug variable hostvars
  ansible.builtin.debug:
    var: hostvars

- name: Get host Default IP addresses
  ansible.builtin.import_tasks: get-host-default-ip-addresses.yml

- name: Get services running on host
  ansible.builtin.import_tasks: get-host-services.yml

- name: Check whether firewalld is running
  ansible.builtin.import_tasks: get-firewall-state.yml
