---

- package_facts: {}

- when: ansible_facts.packages | length < 1
  block:

  - name: "check if {{ package }} is installed"
    yum:
      list="{{ package }}"
    register: is_installed
    when: ansible_pkg_mgr == 'yum'

  - name: "check if {{ package }} is installed"
    apt:
      list="{{ package }}"
    register: is_installed
    when: ansible_pkg_mgr == 'apt'

# pkg.results|selectattr("yumstate", "match", "installed")|list|length != 0

# - package_facts: {}
# - when: ansible_facts.packages["mysql57-community-release"] is undefined
#   block:
#   - yum:  