---
- name: Install Python modules
  block:
    #  for compatability with gerrlingguy.pip
    - name: Define python modules to install
      ansible.builtin.set_fact:
        pip_install_packages: "{{ python_modules }}"

    - name: Install pip
      become: "{{ ( ansible_os_family | lower ) != 'darwin' }}"
      ansible.builtin.import_role:
        name: geerlingguy.pip
      tags:
        - pip

  when: python_modules is defined and ( python_modules | length > 0 )
