---
# tasks file for ansible-role-configure-host

- name: Run package update
  ansible.builtin.import_tasks: run-package-update.yml
  tags:
    - base
    - dependencies

- name: Install base dependencies
  ansible.builtin.import_tasks: install-dependencies.yml
  tags:
    - base
    - dependencies

- name: Configure local storage
  ansible.builtin.import_tasks: configure-storage.yml
  tags:
    - base
    - storage
