---
- name: "Set hostname to {{ hostvars[inventory_hostname].ansible_host }}"
  become: yes
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname].ansible_host }}"
  when:
    - hostvars[inventory_hostname].ansible_host is defined
    - hostvars[inventory_hostname].ansible_host != 'localhost'
