---

# src: http://derpturkey.com/setting-host-with-ansible-in-ubuntu/
- name: Update hostname in /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1    {{ ansible_hostname }}'
    state: present

# src: https://gist.github.com/rothgar/8793800
- name: Update hosts file
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_' + cluster_iface]['ipv4']['address'] }} {{item}}"
    state: present
    backup: yes
  when:
    - hostvars[item]['ansible_' + cluster_iface]['ipv4']['address'] is defined
  loop: "{{ groups['all'] | flatten(levels=1) }}"
