---
- name: Converge
  hosts: all
  become: yes

  vars:

    update_cache_only: no

  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  tasks:

    - name: "Include ansible-role-configure-host"
      include_role:
        name: "ansible-role-configure-host"
